In [46]:
import pandas as pd
import sqlite3

In [47]:
# Creating database connection
conn = sqlite3.connect("../database/RoadAccident.db")

In [48]:
# Checking tables in the database
tables = pd.read_sql_query("select name from sqlite_master where type='table'", conn)
tables

              name
0  RoadAccidentSQL

In [49]:
# Iterates through all database tables to display 
# their record count and a preview of the first few rows 
# for data validation.

for table in tables["name"]:
    print('-' * 50, table, '-' * 50)

    count_df = pd.read_sql(
        f"SELECT COUNT(*) AS count FROM {table}",
        conn
    )
    print("Count of records:", count_df["count"].iloc[0])

    display(
        pd.read_sql(
            f"SELECT * FROM {table} LIMIT 5",
            conn
        )
    )

-------------------------------------------------- RoadAccidentSQL --------------------------------------------------
Count of records: 307973

,accident_index,accident_date,day_of_week,junction_control,junction_detail,accident_severity,light_conditions,local_authority,carriageway_hazards,number_of_casualties,number_of_vehicles,police_force,road_surface_conditions,road_type,speed_limit,time,urban_or_rural_area,weather_conditions,vehicle_type
0,BS0000001,01-01-2021,Thursday,Give way or uncontrolled,T or staggered junction,Serious,Daylight,Kensington and Chelsea,None,1,2,Metropolitan Police,Dry,One way street,30,15:11,Urban,Fine no high winds,Car
1,BS0000002,05-01-2021,Monday,Give way or uncontrolled,Crossroads,Serious,Daylight,Kensington and Chelsea,None,11,2,Metropolitan Police,Wet or damp,Single carriageway,30,10:59,Urban,Fine no high winds,Taxi/Private hire car
2,BS0000003,04-01-2021,Sunday,Give way or uncontrolled,T or staggered junction,Slight,Daylight,Kensington and Chelsea,None,1,2,Metropolitan Police,Dry,Single carriageway,30,14:19,Urban,Fine no high winds,Taxi/Private hire car
3,BS0000004,05-01-2021,Monday,Auto traffic signal,T or staggered junction,Serious,Daylight,Kensington and Chelsea,None,1,2,Metropolitan Police,Frost or ice,Single carriageway,30,08:10,Urban,Other,Motorcycle over 500cc
4,BS0000005,06-01-2021,Tuesday,Auto traffic signal,Crossroads,Serious,Darkness - lights lit,Kensington and Chelsea,None,1,2,Metropolitan Police,Dry,Single carriageway,30,17:25,Urban,Fine no high winds,Car

## KPI´S

In [50]:
# Calculating the total number of casualties from the RoadAccidentSQL table

Total_Casualties = pd.read_sql_query("""
    SELECT SUM(number_of_casualties) AS CY_Casualties
                                  FROM RoadAccidentSQL
                                  """, conn)
Total_Casualties

   CY_Casualties
0         417883

In [51]:
Total_Casualties_2022 = pd.read_sql_query("""
    SELECT SUM(number_of_casualties) AS CY_Casualties_2021
    FROM RoadAccidentSQL
    WHERE substr(accident_date, -4) = '2021'
""", conn)

Total_Casualties_2022

   CY_Casualties_2021
0              222146

In [52]:
Total_Casualties_2022 = pd.read_sql_query("""
    SELECT SUM(number_of_casualties) AS CY_Casualties_2022
    FROM RoadAccidentSQL
    WHERE substr(accident_date, -4) = '2022'
""", conn)

Total_Casualties_2022

   CY_Casualties_2022
0              195737

In [53]:
# Calculating the total number of casualties from the RoadAccidentSQL table where the accident severity is 'Fatal'

Fatal_Casualities = pd.read_sql_query("""
    SELECT SUM(number_of_casualties) AS CY_Fatal_Casualties
                                  FROM RoadAccidentSQL
                                WHERE accident_severity = 'Fatal' 
                                  """, conn)
Fatal_Casualities

   CY_Fatal_Casualties
0                 7135

In [54]:
# Calculating the total number of casualties from the RoadAccidentSQL table where the accident severity is 'Serious'

Serious_Casualities = pd.read_sql_query("""
    SELECT SUM(number_of_casualties) AS CY_Serious_Casualties
                                  FROM RoadAccidentSQL
                                WHERE accident_severity = 'Serious' 
                                  """, conn)
Serious_Casualities

   CY_Serious_Casualties
0                  59312

In [ ]:
# Calculating the total number of casualties from the RoadAccidentSQL table where the accident severity is 'Slight'

Slight_Casualities = pd.read_sql_query("""
    SELECT SUM(number_of_casualties) AS CY_Slight_Casualties
                                  FROM RoadAccidentSQL
                                WHERE accident_severity = 'Slight' 
                                  """, conn)
Slight_Casualities

   CY_Slight_Casualties
0                351436